# Generated by Django 5.2.7 on 2025-10-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cycle_length', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flow_intensity', models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='none', max_length=10)),
                ('cramps', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('mood_swings', models.BooleanField(default=False)),
                ('fatigue', models.BooleanField(default=False)),
                ('bloating', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='Tracker.cycle')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cycle', 'date')},
            },
        ),
    ]
